/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.showdomilhao;

import com.showdomilhao.dao.JogadorDAO;
import com.showdomilhao.dao.PartidaDAO;
import com.showdomilhao.model.Jogador;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class TelaRanking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRanking.class.getName());
    private JogadorDAO jogadorDAO = new JogadorDAO();
    private PartidaDAO partidaDAO = new PartidaDAO();
    private DefaultTableModel modeloRanking;
    private DefaultTableModel modeloHistJogos;
    private DefaultTableModel modeloHistChave;
    private List<Jogador> jogadoresRanking; // cache para pegar o ID pela linha
    private TelaInicio telaPai;
    /**
     * Creates new form TelaRanking
     */
    public TelaRanking(TelaInicio pai) {
        initComponents();
                this.telaPai = pai;
        configurarTabelas();
        carregarTudo();
        this.pack();
        this.setLocationRelativeTo(null);
    }
    private void configurarTabelas() {
        // Tabela ranking
        modeloRanking = new DefaultTableModel(
            new String[]{"#", "🏅", "Nome", "Melhor Prêmio"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblRanking.setModel(modeloRanking);
        tblRanking.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblRanking.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblRanking.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblRanking.getColumnModel().getColumn(3).setPreferredWidth(140);
        tblRanking.setRowHeight(28);

        // Tabela histórico de jogos
        modeloHistJogos = new DefaultTableModel(
            new String[]{"Jogador", "Prêmio", "Data"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblHistoricoJogos.setModel(modeloHistJogos);

        // Tabela histórico de chaveamento
        modeloHistChave = new DefaultTableModel(
            new String[]{"Jogador 1", "Jogador 2", "Vencedor", "Data"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblHistoricoChaveamento.setModel(modeloHistChave);
    }

    public void carregarTudo() {
        carregarRanking();
        carregarChaveamento();
        carregarHistorico();
    }

    private void carregarRanking() {
        try {
            modeloRanking.setRowCount(0);
            jogadoresRanking = jogadorDAO.listarRanking();
            for (int i = 0; i < jogadoresRanking.size(); i++) {
                Jogador j = jogadoresRanking.get(i);
                int pos = i + 1;
                modeloRanking.addRow(new Object[]{
                    pos,
                    j.getMedalha(pos),
                    j.getNome(),
                    ControladorJogo.formatarPremio(j.getPontuacao())
                });
            }
        } catch (SQLException e) {
            lblStatusRanking.setText("Erro ao carregar ranking.");
        }
    }

private void carregarChaveamento() {
    try {
        List<Jogador> lista = jogadorDAO.listarTodos();
        // Cast para JComboBox sem tipo para aceitar objetos Jogador
        javax.swing.JComboBox combJ1 = cmbJ1;
        javax.swing.JComboBox combJ2 = cmbJ2;
        combJ1.removeAllItems();
        combJ2.removeAllItems();
        for (Jogador j : lista) {
            combJ1.addItem(j);
            combJ2.addItem(j);
        }
    } catch (SQLException e) {
        System.err.println("Erro ao carregar chaveamento.");
    }
}

    private void carregarHistorico() {
        try {
            modeloHistJogos.setRowCount(0);
            for (Object[] linha : partidaDAO.listarHistoricoJogos())
                modeloHistJogos.addRow(linha);

            modeloHistChave.setRowCount(0);
            for (Object[] linha : partidaDAO.listarHistoricoChaveamento())
                modeloHistChave.addRow(linha);
        } catch (SQLException e) {
            System.err.println("Erro ao carregar histórico.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        pnlAbaRanking = new javax.swing.JPanel();
        pnlBotoesRanking = new javax.swing.JPanel();
        btnResetRanking = new javax.swing.JButton();
        btnRemoverJogador = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        lblStatusRanking = new javax.swing.JLabel();
        pnlAbaChaveamento = new javax.swing.JPanel();
        pnlSelecao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbJ1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbJ2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdJ1Venceu = new javax.swing.JRadioButton();
        rdJ2Venceu = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmarPartida = new javax.swing.JButton();
        lblResultadoChave = new javax.swing.JLabel();
        pnlAbaHistorico = new javax.swing.JPanel();
        tabHistorico = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistoricoJogos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistoricoChaveamento = new javax.swing.JTable();
        btnLimparHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Raking - Show do Milhão");
        setMaximumSize(new java.awt.Dimension(700, 520));
        setMinimumSize(new java.awt.Dimension(700, 520));
        setPreferredSize(new java.awt.Dimension(700, 520));

        pnlTopo.setBackground(new java.awt.Color(26, 35, 126));
        pnlTopo.setMaximumSize(new java.awt.Dimension(0, 70));
        pnlTopo.setMinimumSize(new java.awt.Dimension(0, 70));
        pnlTopo.setPreferredSize(new java.awt.Dimension(0, 70));
        pnlTopo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 215, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ranking - Show do Milhão");
        pnlTopo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        pnlTopo.add(btnVoltar, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlTopo, java.awt.BorderLayout.PAGE_START);

        pnlAbaRanking.setLayout(new java.awt.BorderLayout());

        pnlBotoesRanking.setLayout(new java.awt.GridLayout(2, 3, 6, 6));

        btnResetRanking.setBackground(new java.awt.Color(244, 67, 54));
        btnResetRanking.setForeground(new java.awt.Color(255, 255, 255));
        btnResetRanking.setText("Resetar Ranking");
        btnResetRanking.addActionListener(this::btnResetRankingActionPerformed);
        pnlBotoesRanking.add(btnResetRanking);

        btnRemoverJogador.setBackground(new java.awt.Color(229, 57, 53));
        btnRemoverJogador.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverJogador.setText("Remover");
        btnRemoverJogador.addActionListener(this::btnRemoverJogadorActionPerformed);
        pnlBotoesRanking.add(btnRemoverJogador);

        pnlAbaRanking.add(pnlBotoesRanking, java.awt.BorderLayout.EAST);

        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRanking.setRowHeight(28);
        tblRanking.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(tblRanking);

        pnlAbaRanking.add(jScrollPane, java.awt.BorderLayout.CENTER);

        lblStatusRanking.setText("Pronto.");
        lblStatusRanking.setMaximumSize(new java.awt.Dimension(0, 30));
        lblStatusRanking.setMinimumSize(new java.awt.Dimension(0, 30));
        lblStatusRanking.setPreferredSize(new java.awt.Dimension(0, 30));
        pnlAbaRanking.add(lblStatusRanking, java.awt.BorderLayout.SOUTH);

        tabPane.addTab("Ranking", pnlAbaRanking);

        pnlAbaChaveamento.setLayout(new java.awt.BorderLayout());

        pnlSelecao.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlSelecao.setLayout(new java.awt.GridLayout(3, 4, 0, 12));

        jLabel1.setText("Jogador 1 :");
        pnlSelecao.add(jLabel1);

        pnlSelecao.add(cmbJ1);

        jLabel2.setText("Jogador 2 :");
        pnlSelecao.add(jLabel2);

        pnlSelecao.add(cmbJ2);

        jLabel3.setText("Vencedor :");
        pnlSelecao.add(jLabel3);

        rdJ1Venceu.setText("Jogador 1 venceu");

        rdJ2Venceu.setText("Jogador 2 venceu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(rdJ1Venceu)
                .addGap(32, 32, 32)
                .addComponent(rdJ2Venceu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdJ1Venceu)
                    .addComponent(rdJ2Venceu))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlSelecao.add(jPanel1);

        pnlAbaChaveamento.add(pnlSelecao, java.awt.BorderLayout.CENTER);

        btnConfirmarPartida.setBackground(new java.awt.Color(76, 175, 80));
        btnConfirmarPartida.setText("Confirmar Resultado");
        btnConfirmarPartida.addActionListener(this::btnConfirmarPartidaActionPerformed);
        jPanel2.add(btnConfirmarPartida);
        jPanel2.add(lblResultadoChave);

        pnlAbaChaveamento.add(jPanel2, java.awt.BorderLayout.SOUTH);

        tabPane.addTab("Chaveamento", pnlAbaChaveamento);

        pnlAbaHistorico.setLayout(new java.awt.BorderLayout());

        tblHistoricoJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jogador", "Prêmio", "Data"
            }
        ));
        jScrollPane1.setViewportView(tblHistoricoJogos);

        tabHistorico.addTab("Jogos", jScrollPane1);

        tblHistoricoChaveamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jogador 1", "Jogador 2", "Vencedor", "Title"
            }
        ));
        jScrollPane2.setViewportView(tblHistoricoChaveamento);

        tabHistorico.addTab("Chaveamento", jScrollPane2);

        pnlAbaHistorico.add(tabHistorico, java.awt.BorderLayout.CENTER);

        btnLimparHistorico.setText("Limpar Historico");
        btnLimparHistorico.addActionListener(this::btnLimparHistoricoActionPerformed);
        pnlAbaHistorico.add(btnLimparHistorico, java.awt.BorderLayout.SOUTH);

        tabPane.addTab("Historico", pnlAbaHistorico);

        getContentPane().add(tabPane, java.awt.BorderLayout.CENTER);
        tabPane.getAccessibleContext().setAccessibleName("Ranking");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
                if (telaPai != null) {
            telaPai.carregarJogadores();
            telaPai.setVisible(true);
        } else {
            new TelaInicio().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnResetRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRankingActionPerformed
        // TODO add your handling code here:
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Zerar pontuação de todos os jogadores?", "Confirmar Reset",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                jogadorDAO.resetarRanking();
                carregarRanking();
                lblStatusRanking.setText("Ranking resetado.");
            } catch (SQLException e) {
                lblStatusRanking.setText("Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnResetRankingActionPerformed

    private void btnRemoverJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverJogadorActionPerformed
        // TODO add your handling code here:
                int linha = tblRanking.getSelectedRow();
        if (linha < 0) { lblStatusRanking.setText("Selecione um jogador."); return; }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Remover jogador selecionado?");
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
        try {
            jogadorDAO.deletar(jogadoresRanking.get(linha).getId());
            carregarTudo(); // atualiza ranking e chaveamento
            lblStatusRanking.setText("Jogador removido.");
        } catch (SQLException e) {
            lblStatusRanking.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverJogadorActionPerformed

    private void btnConfirmarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPartidaActionPerformed
        // TODO add your handling code here:
// CORRETO
Jogador j1 = cmbJ1.getSelectedItem() instanceof Jogador ? (Jogador) cmbJ1.getSelectedItem() : null;
Jogador j2 = cmbJ2.getSelectedItem() instanceof Jogador ? (Jogador) cmbJ2.getSelectedItem() : null;
        if (j1 == null || j2 == null || j1.getId() == j2.getId()) {
            lblResultadoChave.setText("⚠ Selecione dois jogadores diferentes.");
            return;
        }
        if (!rdJ1Venceu.isSelected() && !rdJ2Venceu.isSelected()) {
            lblResultadoChave.setText("⚠ Selecione o vencedor.");
            return;
        }
        Jogador vencedor = rdJ1Venceu.isSelected() ? j1 : j2;
        Jogador perdedor = rdJ1Venceu.isSelected() ? j2 : j1;
        try {
            partidaDAO.registrarPartida(j1.getId(), j2.getId(), vencedor.getId());
            jogadorDAO.adicionarPontos(vencedor.getId(), 3);  // +3 por vitória
            jogadorDAO.adicionarPontos(perdedor.getId(), 1);  // +1 por participação
            lblResultadoChave.setText("✅ " + vencedor.getNome() + " venceu! +3pts");
            carregarTudo(); // atualiza ranking e histórico em tempo real
        } catch (SQLException e) {
            lblResultadoChave.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarPartidaActionPerformed

    private void btnLimparHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparHistoricoActionPerformed
        // TODO add your handling code here:
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Apagar todo o histórico?", "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                partidaDAO.limparHistorico();
                carregarHistorico();
            } catch (SQLException e) {
                System.err.println("Erro ao limpar histórico: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLimparHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRanking(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPartida;
    private javax.swing.JButton btnLimparHistorico;
    private javax.swing.JButton btnRemoverJogador;
    private javax.swing.JButton btnResetRanking;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbJ1;
    private javax.swing.JComboBox<String> cmbJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResultadoChave;
    private javax.swing.JLabel lblStatusRanking;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAbaChaveamento;
    private javax.swing.JPanel pnlAbaHistorico;
    private javax.swing.JPanel pnlAbaRanking;
    private javax.swing.JPanel pnlBotoesRanking;
    private javax.swing.JPanel pnlSelecao;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JRadioButton rdJ1Venceu;
    private javax.swing.JRadioButton rdJ2Venceu;
    private javax.swing.JTabbedPane tabHistorico;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblHistoricoChaveamento;
    private javax.swing.JTable tblHistoricoJogos;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables
}
