/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.showdomilhao;



import com.showdomilhao.dao.JogadorDAO;
import com.showdomilhao.model.Jogador;
import java.sql.SQLException;
import java.util.List;
/**
 *
 * @author gusta
 */
public class TelaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicio.class.getName());
    
    
        private JogadorDAO jogadorDAO = new JogadorDAO();

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        carregarJogadores();
        this.pack();
        this.setLocationRelativeTo(null);
    }
public void carregarJogadores() {
    try {
        // Cast para JComboBox sem tipo para aceitar objetos Jogador
        javax.swing.JComboBox combo = cmbJogadores;
        combo.removeAllItems();
        combo.addItem("-- selecione --");
        List<Jogador> lista = jogadorDAO.listarTodos();
        for (Jogador j : lista) combo.addItem(j);
    } catch (SQLException e) {
        System.err.println("Erro ao carregar jogadores: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        lblInstrucao = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblOu = new javax.swing.JLabel();
        cmbJogadores = new javax.swing.JComboBox<>();
        btnJogar = new javax.swing.JButton();
        pnlRodape = new javax.swing.JPanel();
        btnVerRanking = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show do Milhão");
        setMaximumSize(new java.awt.Dimension(450, 350));
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);

        pnlTopo.setBackground(new java.awt.Color(26, 35, 126));
        pnlTopo.setMaximumSize(new java.awt.Dimension(0, 90));
        pnlTopo.setMinimumSize(new java.awt.Dimension(0, 90));
        pnlTopo.setPreferredSize(new java.awt.Dimension(0, 90));
        pnlTopo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 215, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SHOW DO MILHÃO");
        pnlTopo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTopo, java.awt.BorderLayout.NORTH);

        pnlForm.setBackground(new java.awt.Color(13, 71, 161));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 10, 30));
        pnlForm.setLayout(new java.awt.GridLayout(5, 1, 0, 12));

        lblInstrucao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInstrucao.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrucao.setText("Digite seu nome :");
        pnlForm.add(lblInstrucao);

        txtNome.setColumns(20);
        txtNome.setMaximumSize(new java.awt.Dimension(234, 22));
        txtNome.setMinimumSize(new java.awt.Dimension(234, 22));
        pnlForm.add(txtNome);

        lblOu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOu.setForeground(new java.awt.Color(204, 204, 204));
        lblOu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOu.setText("Ou selecione um jogador existente :");
        pnlForm.add(lblOu);

        cmbJogadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlForm.add(cmbJogadores);

        btnJogar.setBackground(new java.awt.Color(255, 215, 0));
        btnJogar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(this::btnJogarActionPerformed);
        pnlForm.add(btnJogar);

        getContentPane().add(pnlForm, java.awt.BorderLayout.CENTER);

        pnlRodape.setBackground(new java.awt.Color(26, 35, 126));
        pnlRodape.setMaximumSize(new java.awt.Dimension(0, 50));
        pnlRodape.setMinimumSize(new java.awt.Dimension(0, 50));
        pnlRodape.setPreferredSize(new java.awt.Dimension(0, 50));
        pnlRodape.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnVerRanking.setText("Ver Ranking");
        btnVerRanking.addActionListener(this::btnVerRankingActionPerformed);
        pnlRodape.add(btnVerRanking);

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        pnlRodape.add(btnSair);

        getContentPane().add(pnlRodape, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        // TODO add your handling code here:
        
        String nome = txtNome.getText().trim();
        Jogador jogador = null;
        
                try {
            if (!nome.isEmpty()) {
                // Criou/encontrou pelo nome digitado
                jogador = jogadorDAO.buscarOuCriar(nome);
            } else if (cmbJogadores.getSelectedIndex() > 0) {
                // Selecionou da lista
                jogador = (Jogador) cmbJogadores.getSelectedItem();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Digite seu nome ou selecione um jogador existente.");
                return;
            }
            new TelaJogo(jogador).setVisible(true);
            this.dispose();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnVerRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRankingActionPerformed
        // TODO add your handling code here:
        
        new TelaRanking(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerRankingActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVerRanking;
    private javax.swing.JComboBox<String> cmbJogadores;
    private javax.swing.JLabel lblInstrucao;
    private javax.swing.JLabel lblOu;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlRodape;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
